apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway:latest
        ports:
        - containerPort: 4001
        env:
        - name: USER_MANAGEMENT_URL
          value: "http://user-management:8000/graphql/"
        - name: COURSE_MANAGEMENT_URL
          value: "http://course-management:3000/graphql"
        - name: ENROLLMENTS_MANAGEMENT_URL
          value: "http://enrollments-management:8001/graphql/"