# Generated by Django 5.0.6 on 2024-06-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="enrollment_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
