# Generated by Django 5.0.6 on 2024-06-18 22:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_enrollment_enrollment_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course")},
        ),
    ]
