# Generated by Django 5.0.6 on 2024-06-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_enrollment_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
